# -*- coding: utf-8 -*-
"""nakul nischal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Z0stfbtoTYtXbDcQ9p5o_rbiz45i7DT
"""

r=int(input("entr the radius of the circle"))
area=3.14*r*r
print("area=",area)



f=str(input("enter the first name "))
g=str(input("enter the last name "))
print(f,g)

x=float(input("Enter the value of x:" ))
y=float(input("enter the value of y:"))
z=(x+y)*(x+y)
print (z)

a=str(input("enter value of a: "))
b=str(input("enter the value of b: "))
c=str(input("enter the value of c: "))
s=(a+b+c)
if a==b or b==c or c==a:
 print("the sum is 0")
else :
 print("the sum is", s)

a=float(input("enter the value of a"))
a=(a%2)
if a==0:
 print("the number is even")
else:
  print("the number is odd")

#Lab 2

import random
b=random.randint(1,10)
for i in range(10):
 a = int(input("Enter a number:"))
 if a == b:
   print("correct")
 else:
   print("incorrect")

for i in range(0,6):
  if (i==3 or i==6):
     continue
  print(i)

z=input("enter the charecter")
if z=='a' or z=='e' or z=='i' or z=='o' or z=='u':
  print("it is a vowel")
else:
  print("it is a consonant")

b=int(input("enter the value"))
for i in range(1,11):
 a=b*i
 print(a)

a=0
b=1
print(b)
while True: 
  c=a+b
  a=b
  b=c
  if c<50:
   print(c)

s=input("enter a string ")
d=l=0
for c in s:
  if  c.isdigit ():
    d=d+1
  elif c.isalpha():
      l=l+1
  else:
    pass
  print("letters",l)
  print("digits",d)

num = int(input("Enter a number: "))

for i in range(1, 11):
   print(num, 'x', i, '=', num*i)

def remove_odd_index_characters(input_string):
    return input_string[::2]

input_string = " print odd index characters"
print("Original string: ", input_string)
output_string = remove_odd_index_characters(input_string)
print("String after removing odd index characters: ", output_string)

def remove_odd_index_characters(input_string):
    return input_string[::1]

input_string=input(" enter print odd index characters ")
print("Original string: ", input_string)
output_string = remove_odd_index_characters(input_string)
print("String after removing odd index characters: ", output_string)

input_string = input("Enter a string: ")
print("Input in uppercase: ", input_string.upper())
print("Input in lowercase: ", input_string.lower())

numbers = [1.2345, -2.3456, 3.4567, -4.5678, 5.6789]

for number in numbers:
    print("{:+.2f}".format(number))

number = 123

print("Left aligned: {:<10}".format(number))
print("Right aligned: {:>10}".format(number))
print("Center aligned: {:^10}".format(number))

a=/content/drive/My

import os
b= os.getcwd()
print(b)

drive.mount9"/content/drive/MyDrive/folder")

import shelve
print(dir(shelve))

import shelve
S=shelve.open('program 4')
S['name']='Nishchal'
S['age']='18'
S['gender']='male'
print(S['name'])
print(S['age'])
print(S['gender'])

import shutil
S=('/content/drive/MyDrive/dir1/hello.py')
a=('/content/drive/Mydrive/dir1/hello.py')
shutil.copy(S,a)

from zipple import Zipfile
with ZipFile('/content/drive/MyDRive/dir1/program4.db,'w')

with ZipFile('/content/drive/MyDrive/dir1/programm.db,'a')as zip
Zip.print dir()
Zip.extract all()
print("Done!")